CREATE TABLE MWA_M_BRANCH (
	ID int NOT NULL,
	BRANCH_CODE varchar(2) NULL,
	BRANCH_TEXT varchar(250) NULL,
	CREATE_BY varchar(20) NULL,
	CREATE_DATE datetime NULL,
	LASTUPDATE_BY varchar(20) NULL,
	LASTUPDATE_DATE datetime NULL,
	ROW_VERSION int NULL);

CREATE TABLE MWA_M_WEEK (
	ID int NOT NULL,
	WEEK_TEXT varchar(250) NULL,
	START_DATE datetime NULL,
	END_DATE datetime NULL,
	NO_OF_WORKDAY int NULL,
	CREATE_BY varchar(20) NULL,
	CREATE_DATE datetime NULL,
	LASTUPDATE_BY varchar(20) NULL,
	LASTUPDATE_DATE datetime NULL,
	ROW_VERSION int NULL);

CREATE TABLE MWA_M_PETITION (
	ID int NOT NULL,
	ACCOUNT_NO varchar(20) NULL,
	PETITION_NO varchar(20) NULL,
	PETITION_DATE datetime NULL,
	BRANCH_ID int NOT NULL,
	WEEK_ID int NOT NULL,
	CREATE_BY varchar(20) NULL,
	CREATE_DATE datetime NULL,
	LASTUPDATE_BY varchar(20) NULL,
	LASTUPDATE_DATE datetime NULL,
	ROW_VERSION int NULL);

CREATE TABLE STD_M_ERROR (
	ID int NOT NULL,
	ERROR_CODE varchar(20) NULL,
	ERROR_TEXT varchar(250) NULL,
	SEVERITY varchar(10) NULL,
	CREATE_BY varchar(20) NULL,
	CREATE_DATE datetime NULL,
	LASTUPDATE_BY varchar(20) NULL,
	LASTUPDATE_DATE datetime NULL,
	ROW_VERSION int NULL);

CREATE TABLE FMW_M_PARAMETER (
	ID int NOT NULL,
	PARAMETER_CODE varchar(30) NULL,
	PARAMETER_VALUE varchar(50) NULL,
	CREATE_BY varchar(20) NULL,
	CREATE_DATE datetime NULL,
	LASTUPDATE_BY varchar(20) NULL,
	LASTUPDATE_DATE datetime NULL,
	ROW_VERSION int NULL);

	
CREATE TABLE UME_M_AUTH_OBJECT(
	ID int NOT NULL,
	AUTH_OBJECT_CODE varchar(20) NOT NULL,
	AUTH_OBJECT_NAME varchar(100) NULL,
	AUTH_FIELD_1 varchar(20) NULL,
	AUTH_FIELD_2 varchar(20) NULL,
	AUTH_FIELD_3 varchar(20) NULL,
	AUTH_FIELD_4 varchar(20) NULL,
	AUTH_FIELD_5 varchar(20) NULL,
	CREATE_BY varchar(20) NULL,
	CREATE_DATE datetime NULL,
	LASTUPATE_BY varchar(20) NULL,
	LASTUPDATE_DATE datetime NULL,
	ROW_VERSION int NULL);
	
CREATE TABLE UME_M_AUTHORIZATION(
	ID int NOT NULL,
	AUTH_CODE varchar(20) NULL,
	AUTH_NAME varchar(200) NULL,
	AUTH_OBJECT_CODE varchar(20) NULL,
	AUTH_FIELD_1_VALUE_FROM varchar(255) NULL,
	AUTH_FIELD_1_VALUE_TO varchar(255) NULL,
	AUTH_FIELD_2_VALUE_FROM varchar(255) NULL,
	AUTH_FIELD_2_VALUE_TO varchar(255) NULL,
	AUTH_FIELD_3_VALUE_FROM varchar(255) NULL,
	AUTH_FIELD_3_VALUE_TO varchar(255) NULL,
	AUTH_FIELD_4_VALUE_FROM varchar(255) NULL,
	AUTH_FIELD_4_VALUE_TO varchar(255) NULL,
	AUTH_FIELD_5_VALUE_FROM varchar(255) NULL,
	AUTH_FIELD_5_VALUE_TO varchar(255) NULL,
	CREATE_BY varchar(20) NULL,
	CREATE_DATE datetime NULL,
	LASTUPDATE_BY varchar(20) NULL,
	LASTUPDATE_DATE datetime NULL,
	ROW_VERSION int NULL);

CREATE TABLE UME_M_MAPPING_AUTH_ROLE(
	ID int NOT NULL,
	AUTH_ID int NOT NULL,
	ROLE_ID int NOT NULL,
	CREATE_BY varchar(20) NULL,
	CREATE_DATE datetime NULL,
	LASTUPATE_BY varchar(20) NULL,
	LASTUPDATE_DATE datetime NULL,
	ROW_VERSION int NULL);
	
CREATE TABLE UME_M_MAPPING_ROLE_USER(
	ID int NOT NULL,
	ROLE_ID int NULL,
	USER_ID int NULL,
	CREATE_BY varchar(20) NULL,
	CREATE_DATE datetime NULL,
	LASTUPATE_BY varchar(20) NULL,
	LASTUPDATE_DATE datetime NULL,
	ROW_VERSION int NULL);
	
CREATE TABLE UME_M_ROLE(
	ID int NOT NULL,
	ROLE_CODE varchar(20) NOT NULL,
	ROLE_NAME varchar(100) NOT NULL,
	CREATE_BY varchar(20) NULL,
	CREATE_DATE datetime NULL,
	LASTUPDATE_BY varchar(20) NULL,
	LASTUPDATE_DATE datetime NULL,
	ROW_VERSION int NULL);
	
CREATE TABLE UME_M_USER(
	ID int NOT NULL,
	USER_CODE varchar(20) NOT NULL,
	USER_NAME varchar(100) NULL,
	PASSWORD varchar(20) NULL,
	CREATE_BY varchar(20) NULL,
	CREATE_DATE datetime NULL,
	LASTUPDATE_BY varchar(20) NULL,
	LASTUPDATE_DATE datetime NULL,
	ROW_VERSION int NULL);
